{{Infobox aircraft type
 |type=Reconnaissance
 |national origin={{flag|German Empire}}
 |manufacturer=[[Aviatik]]
 |designer=[[Deutsche Flugzeugwerke]]
 |first flight=1916
 |introduced=1916
 |retired=
 |status=
 |primary user=[[Luftstreitkräfte]]
 |produced=1916-1918
 |number built=3250
 |program cost=<!--should be used only for experimental programs-->
 |unit cost=
 |developed from=
 |variants with their own articles=
}}