{{Infobox Aircraft Type
 |type=Bomber
 |manufacturer=[[Deutsche Flugzeug-Werke|DFW]]
 |designer=
 |first flight=1916
 |introduced=
 |retired=
 |status=
 |primary user=''[[Luftstreitkräfte]]''
 |more users=
 |produced=
 |number built=1<ref name="Gray">{{cite book|last=Gray|first=Peter|author2=Owen Thetford|title=German Aircraft of the First World War|publisher=Putnam|location=London|year=1970|edition=2nd|isbn=0-370-00103-6}}</ref>
 |variants with their own articles=
}}