{{Infobox Aircraft Type
 |type=Reconnaissance aircraft
 |manufacturer=[[Fokker]]
 |designer=
 |first flight=1918<ref name="Donald">{{cite encyclopedia | editor = Donald, David | encyclopedia =The Encyclopedia of World Aircraft | volume = | pages = pg 427| publisher = Prospero Books | date = 1997 | id = ISBN 1-85605-375-X | accessdate = }}</ref>
 |introduced=
 |retired=
 |status=
 |primary user=
 |more users=
 |produced=
 |number built=250+
 |variants with their own articles=
}}