{{Infobox Aircraft Type
 | type=Small airliner
 | national origin=[[Germany]]
 | manufacturer=[[Stahlwerk-Mark]]
 | designer=Rieseler brothers
 | first flight=1923
 | introduced=
 | retired=
 | status=
 | primary user=
 | more users= <!--Limited to three in total; separate using <br /> -->
 | produced= <!--years in production-->
 | number built=2
 | program cost= <!--Total program cost-->
 | unit cost= <!--Incremental or flyaway cost for military or retail price for commercial aircraft-->
 | developed from= 
 | variants with their own articles=
}}