{{Infobox aircraft type
 | type=[[Bomber]]
 | national origin= [[Germany]]
 | manufacturer= [[Schütte-Lanz]]
 | designer= [[Graf von Zeppelin]]
 | first flight=[[1917 in aviation|1917]]
 | introduced=
 | retired=
 | status=
 | primary user=''[[Luftstreitkräfte]]''
 | more users= <!--Limited to three in total; separate using <br /> -->
 | produced= <!--years in production-->
 | number built=3
 | program cost= <!--Total program cost-->
 | unit cost= <!--Incremental or flyaway cost for military or retail price for commercial aircraft-->
 | developed from=
 | variants with their own articles=[[Zeppelin-Staaken R.VII]], [[Zeppelin-Staaken R.XIV]], [[Zeppelin-Staaken R.XV]], [[Zeppelin-Staaken R.XVI]], 
}}